sonar.projectKey=gautam1001_LiveWeather
sonar.organization=gautam1001
sonar.host.url=https://sonarcloud.io

sonar.projectName=LiveWeather
sonar.sourceEncoding=UTF-8

sonar.sources=LiveWeather,Packages
sonar.tests=LiveWeatherTests,Packages/Data/Tests,Packages/Domain/Tests,Packages/Presentation/Tests
sonar.exclusions=**/.build/**,**/DerivedData/**,**/xcuserdata/**,**/*.xcuserstate,**/resource_bundle_accessor.swift
